version: '3.4'

services:
  tolitech.codegenerator.logging.database.sqlserver:
    container_name: tolitech.codegenerator.logging.database.sqlserver
    image: ${DOCKER_REGISTRY-}tolitech.codegenerator.logging.database.sqlserver
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "1433:1433"